- wallabagger/css/popup.css
> Adding space for the tags suggestions box

- wallabagger/css/popup.css
- wallabagger/js/popup.js
- wallabagger/manifest.json
- wallabagger/popup.html
1) improves @Simounet fix to issue #11 
2) keyboard shortcut Alt+w - works in chrome and in FF  version > 52
3) restore lost changes in delete confirmation dialog
> Preparing to add extension to firefox add-ons

- wallabagger/js/background.js
- wallabagger/manifest.json
> Hotkey for background saving, works in FF-stable

- wallabagger/js/background.js
> Adds context menu items to goto wbg pages, see #17

- wallabagger/js/popup.js
Allow insert new tag without waiting for real saving
> Fast work with tags - optimistic tagging - for #16

- wallabagger/js/options.js
- wallabagger/options.html
> Options - clear, save and load data

- wallabagger/css/popup.css
- wallabagger/js/popup.js
Fixes duplicate tags with "." and adding empty tags
> fixes #30 and #31

- wallabagger/js/options.js
- wallabagger/js/popup.js
> Fix #55 innerText and innerHTML removed

- wallabagger/js/popup.js
1) set focus on the title edit input after icon clicking
2) toggles edit input visibility by clicking icon
> Small title edit improvements

- wallabagger/css/popup.css
- wallabagger/js/popup.js
Just for keyboard fans like me!
> select tag in found tags by ctrl-left-and-right-arrows

- wallabagger/_locales/en/messages.json
- wallabagger/_locales/fr/messages.json
- wallabagger/js/background.js
- wallabagger/js/common.js
- wallabagger/js/options.js
- wallabagger/js/popup.js
- wallabagger/manifest.json
- wallabagger/options.html
- wallabagger/popup.html
With this one, we can handle translations into our extension. For now 🇺🇸 and 🇫🇷 . You can add 🇷🇺 @Rurik19! 😄
I wanted to use modules but I'm not sure about Edge handling it and I don't have any Windows right now.
> Translations

- wallabagger/_locales/en/messages.json
- wallabagger/_locales/fr/messages.json
- wallabagger/_locales/ru/messages.json
- wallabagger/js/common.js
- wallabagger/js/options.js
@Simounet please look at this PR, there are changes in the code.
> Russian i18n

- wallabagger/js/background.js
Improving using cache, service URLs and removing anchors from URLs
> fix #117 and #3157 of wallabag: to many exists check

- wallabagger/_locales/ru/messages.json
this is the just little fix, before release 1.4.5
> fix placeholder for tagsInput

- wallabagger/js/popup.js
See #133 for more informations :)
> Fixes HTML entities decoding (closes #133)

- wallabagger/js/background.js
> Stop leaking URL of private tab

- wallabagger/_locales/ja/messages.json
I translated all strings in "/en/messages.json" into Japanese and saved it as "/ja/messages.json".
> add Japanese translation

- wallabagger/_locales/ja/messages.json
> update japanese translation

- wallabagger/_locales/de/messages.json
- wallabagger/_locales/en/messages.json
- wallabagger/_locales/fr/messages.json
- wallabagger/_locales/ja/messages.json
- wallabagger/_locales/ru/messages.json
- wallabagger/_locales/zh/messages.json
- wallabagger/js/background.js
- wallabagger/js/common.js
- wallabagger/js/options.js
- wallabagger/js/wallabag-api.js
- wallabagger/manifest.json
- wallabagger/options.html
Fix #194 .
@Rurik19  @AKKED @jacobkiers @88431844, could you update your translation files and do a PR on this `feat/reduce-permissions` branch please?
> Reduce permissions

- wallabagger/js/options.js
Avoiding wrong copy paste from the API keys page.
Resolves #210
> Input values trimmed

- wallabagger/_locales/en/messages.json
- wallabagger/js/options.js
- wallabagger/js/wallabag-api.js
- wallabagger/options.html
This commit adds option to fetch locally by default.
This PR extends #300, it will add option to set fetching content by default so user doesn't need to specify websites, it will fetch all by default.
Related issues:
#309
> adds an option to fetch locally by default

- README.md
Corrected link to setup tutorial. :)
> Update README.md - Broken tutorial link fix.
